# GET ALL --
#///////////////////////////////////////////////////////////////
# GET ALL DECEASED FEMALE
###
GET https://familyroutes-abts.onrender.com/dFemales HTTP/1.1
# GET ALL DECEASED MALE
###
GET https://familyroutes-abts.onrender.com/dMales HTTP/1.1
# GET ALL LIVE FEMALE
###
GET https://familyroutes-abts.onrender.com/lFemales HTTP/1.1
# GET ALL LIVE MALE
###
GET https://familyroutes-abts.onrender.com/lMales HTTP/1.1
# GET ALL USERS
###
GET https://familyroutes-abts.onrender.com/users HTTP/1.1

# GET SINGLE -- need to paste in an id from above to get by ID. 
#///////////////////////////////////////////////////////////////
# GET SINGLE DECEASED FEMALE
###
GET  https://familyroutes-abts.onrender.com/dFemales/648dd1ad472c91115ef9324b HTTP/1.1
# GET SINGLE DECEASED MALE
###
GET ALL https://familyroutes-abts.onrender.com/dMales/648dd0b7472c91115ef93249 HTTP/1.1
# GET SINGLE LIVE FEMALE
###
GET ALL https://familyroutes-abts.onrender.com/lFemales/648dcb88472c91115ef9323d HTTP/1.1
# GET SINGLE LIVE MALE
###
GET ALL https://familyroutes-abts.onrender.com/lMales/648dc7f0472c91115ef93234 HTTP/1.1
# GET SINGLE USER
###
GET ALL https://familyroutes-abts.onrender.com/users/648de1da9fdb950e5f492e91 HTTP/1.1

### POST add DECEASED FEMALE to database 
//POST http://localhost:8080/dFemales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/dFemales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Lorna",
    "lastName": "Dane",
    "birthYear": "1864",
    "birthLocation": "Chickasaw Bayou, Mississippi",
    "deathYear": "1967",
    "deathLocation": "Santa Monica, California",
    "children": "Yes"
}

### POST add DECEASED MALE to database 
//POST http://localhost:8080/dMales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/dMales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Max",
    "lastName": "Eisenhardt",
    "birthYear": "1926",
    "birthLocation": "Wayland, Ohio",
    "deathYear": "2008",
    "deathLocation": "Wetzel, West Virginia"
}

### POST add LIVING FEMALE to database 
//POST http://localhost:8080/lFemales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/lFemales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Eleanor",
    "lastName": "Camacho",
    "birthYear": "1980",
    "birthLocation": "Adair, Kentucky"
}

### POST add LIVING MALE to database 
//POST http://localhost:8080/lMales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/lMales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Kurt",
    "lastName": "Wagner",
    "birthYear": "1992",
    "birthLocation": "Pippin Lake, Ohio"
}

###
DELETE  http://localhost:8080/dFemales/648dd1ad472c91115ef9324b
//DELETE https://familyroutes-abts.onrender.com/dFemales/648dd1ad472c91115ef9324b

###
//POST http://localhost:8080/dMales/648dd0b7472c91115ef93249
DELETE https://familyroutes-abts.onrender.com/dMales/648dd0b7472c91115ef93249

###
//POST http://localhost:8080/lFemales/648dcb88472c91115ef9323d
DELETE https://familyroutes-abts.onrender.com/lFemales/648dcb88472c91115ef9323d

###
//POST http://localhost:8080/dMales/648dc7f0472c91115ef93234
DELETE https://familyroutes-abts.onrender.com/dMales/648dc7f0472c91115ef93234


//Dead Males PUT Request
###
PUT https://familyroutes-abts.onrender.com/dMales/648dce7e472c91115ef93244
Content-Type: application/json

{
    "firstName": "Don",
    "lastName": "Payne",
    "birthYear": "1964",
    "birthLocation": "Milkriver, Canada"
}
//Dead FeMales PUT Request
###
PUT https://familyroutes-abts.onrender.com/dFemales/648dd1ad472c91115ef9324b
Content-Type: application/json

{
    "firstName": "Dannel",
    "lastName": "Walton",
    "birthYear": "1884",
    "birthLocation": "BearLake, Idaho"
}
//living Males PUT Request
###
PUT https://familyroutes-abts.onrender.com/lMales/648dc7f0472c91115ef93234
Content-Type: application/json

{
    "firstName": "Donald",
    "lastName": "Kemper",
    "birthYear": "1962",
    "birthLocation": "Taber, Canada"
}
//living Females PUT Request
###
PUT https://familyroutes-abts.onrender.com/lFemales/648dcaab472c91115ef9323b
Content-Type: application/json

{
    "firstName": "Jennifer",
    "lastName": "Ogden",
    "birthYear": "1981",
    "birthLocation": "Calgary, Canada"
}

