//Localhost
###
GET https://localhost:8080/dFemales HTTP/1.1
# GET ALL DECEASED MALE
###
GET https://localhost:8080/dMales HTTP/1.1
# GET ALL LIVE FEMALE
###
GET http://localhost:8080/lFemales HTTP/1.1
# GET ALL LIVE MALE
###
GET http://localhost:8080/lMales HTTP/1.1
# GET ALL USERS
###
GET http://localhost:8080/users HTTP/1.1

# GET SINGLE -- need to paste in an id from above to get by ID. 
#///////////////////////////////////////////////////////////////
# GET SINGLE DECEASED FEMALE
###
GET  http://localhost:8080/dFemales/648dd1ad472c91115ef9324b HTTP/1.1
# GET SINGLE DECEASED MALE
###
GET ALL http://localhost:8080/dMales/648dd0b7472c91115ef93249 HTTP/1.1
# GET SINGLE LIVE FEMALE
###
GET ALL http://localhost:8080/lFemales/648dcb88472c91115ef9323d HTTP/1.1
# GET SINGLE LIVE MALE
###
GET ALL http://localhost:8080/lMales/648dc7f0472c91115ef93234 HTTP/1.1
# GET SINGLE USER
###
GET ALL http://localhost:8080/users/648de1da9fdb950e5f492e91 HTTP/1.1



###
DELETE http://localhost:8080/dFemales/648dd1ad472c91115ef9324b

###
DELETE http://localhost:8080/dMales/648dd0b7472c91115ef93249

###
DELETE http://localhost:8080/lFemales/648dcb88472c91115ef9323d

###
DELETE http://localhost:8080/lMales/648dc7f0472c91115ef93234



//Production

# GET ALL --
#///////////////////////////////////////////////////////////////
# GET ALL DECEASED FEMALE
###
GET https://familyroutes-abts.onrender.com/dFemales HTTP/1.1
# GET ALL DECEASED MALE
###
GET https://familyroutes-abts.onrender.com/dMales HTTP/1.1
# GET ALL LIVE FEMALE
###
GET https://familyroutes-abts.onrender.com/lFemales HTTP/1.1
# GET ALL LIVE MALE
###
GET https://familyroutes-abts.onrender.com/lMales HTTP/1.1
# GET ALL USERS
###
GET https://familyroutes-abts.onrender.com/users HTTP/1.1

# GET SINGLE -- need to paste in an id from above to get by ID. 
#///////////////////////////////////////////////////////////////
# GET SINGLE DECEASED FEMALE
###
GET  https://familyroutes-abts.onrender.com/dFemales/648dd1ad472c91115ef9324b HTTP/1.1
# GET SINGLE DECEASED MALE
###
GET ALL https://familyroutes-abts.onrender.com/dMales/648dd0b7472c91115ef93249 HTTP/1.1
# GET SINGLE LIVE FEMALE
###
GET ALL https://familyroutes-abts.onrender.com/lFemales/648dcb88472c91115ef9323d HTTP/1.1
# GET SINGLE LIVE MALE
###
GET ALL https://familyroutes-abts.onrender.com/lMales/648dc7f0472c91115ef93234 HTTP/1.1
# GET SINGLE USER
###
GET ALL https://familyroutes-abts.onrender.com/users/648de1da9fdb950e5f492e91 HTTP/1.1



### POST add DECEASED FEMALE to database 
//POST http://localhost:8080/dFemales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/dFemales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Pauline",
    "lastName": "Cook",
    "birthYear": "1919",
    "birthLocation": "Chickasaw Bayou, Mississippi",
    "deathYear": "1978",
    "deathLocation": "Santa Monica, California",
    "children": "Yes"
}

### POST add DECEASED MALE to database 
//POST http://localhost:8080/dMales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/dMales HTTP/1.1
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Heighton",
    "birthYear": "1926",
    "birthLocation": "Wayland, Ohio",
    "deathYear": "2008",
    "deathLocation": "Wetzel, West Virginia"
}

### POST add LIVING FEMALE to database 
//POST http://localhost:8080/lFemales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/lFemales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Genievieve",
    "lastName": "St.Pierre",
    "birthYear": "1980",
    "birthLocation": "Adair, Kentucky"
}

### POST add LIVING MALE to database 
//POST http://localhost:8080/lMales HTTP/1.1 
POST https://familyroutes-abts.onrender.com/lMales HTTP/1.1
Content-Type: application/json

{
    "firstName": "Marius",
    "lastName": "Herbert",
    "birthYear": "1992",
    "birthLocation": "Pippin Lake, Ohio"
}

###
DELETE https://familyroutes-abts.onrender.com/dFemales/648dd1ad472c91115ef9324b

###
DELETE https://familyroutes-abts.onrender.com/dMales/648dd0b7472c91115ef93249

###
DELETE https://familyroutes-abts.onrender.com/lFemales/648dcb88472c91115ef9323d

###
DELETE https://familyroutes-abts.onrender.com/dMales/648dc7f0472c91115ef93234





